### ISSUE TITLE
compile warnings from JWT pod

### ISSUE THREAD

**Issue by mylyuic** [firebase/digits-migration-helper-ios#1]
Seeing compile warnings while using the pod.
Examples are

```
Showing Recent Issues
/Users/yongmao/test/test-ios-sdk/Pods/JWT/Classes/Algorithms/Holders/JWTAlgorithmDataHolder.m:39:17: Auto property synthesis will not synthesize property 'currentSecretData' declared in protocol 'JWTAlgorithmDataHolder'
```

Here is a screenshot

![image](https://cloud.githubusercontent.com/assets/883082/26180203/e3d5e4c6-3b1c-11e7-8103-0d5faaf78e9a.png)

**Comment by ianbarber** [comment]
Might be better to file this one on the JWT library directly: https://github.com/yourkarma/JWT
