### ISSUE TITLE
FIRDigitsSessionStore -> getSession() crash

### ISSUE THREAD

**Issue by aetsyss** [firebase/digits-migration-helper-ios#2]
Hello,
I copied this function from the migration manual (https://firebase.google.com/support/guides/digits-ios)

```
let migrator = DigitsMigrator.init(digitsAppConsumerKey: key as! String, withDigitsAppConsumerSecret: secret as! String)

migrator.getLegacyAuth { (customSignInToken, session) in
  if let customSignInToken = customSignInToken {
    print("Legacy digits session detected: token=\(customSignInToken), session=\(DigitsSession.describe(session))")

    Auth.auth().signIn(withCustomToken: customSignInToken) { (user, error) in
      if let error = error {
        print("signInWithCustomToken, user=\(String(describing: user)), error=\(error)")
        return
      }

      migrator.clearLegacyAuth { (success, error) in
        print("clearLegacyAuth, success=\(success), error=\(error?.localizedDescription ?? "")")
      }
    }
  }
}
```

and call it from my AppDelegate's didFinishLaunchingWithOptions.
But when I start the app it's crashed highlighting the 

`return [NSKeyedUnarchiver unarchiveObjectWithData:latest.data];`

line in the 

```
- (FIRDigitsSession*) getSession {
  NSArray *unsorted = [self getItems];
  NSArray *sorted = [self sortKeychainItemsByDate:unsorted];
  FIRDigitsKeychainItem *latest = sorted.lastObject;

  if (latest) {
    return [NSKeyedUnarchiver unarchiveObjectWithData:latest.data];
  } else {
    return nil;
  }
}
```

instance method of the FIRDigitsSessionStore class.
Watch the screenshot attached.

<img width="1435" alt="screen shot 2017-05-25 at 11 59 05" src="https://cloud.githubusercontent.com/assets/1741819/26443923/f9070b5a-4142-11e7-8e53-796cbc308487.png">

**Comment by mylyuic** [comment]
@aetsyss , thanks for reporting the issue. I could not reproduce the crashing issue using the sample app included in the repo.

So in your environment, do you still have Digits sdk included in the app? If it's running in a simulator, would you be able to reset the simulator and test the app with some of these scenarios?

1 . Don't log into Digits.
2 . Log into Digits and then restart the app, which would trigger the token conversion process. 

I would like to see if the crash can be reproduced in the above 2 scenarios.

**Comment by aetsyss** [comment]
Hello @mylyuic,
No, I'd removed the Digits SDK from my project before a had the crash. So I can't follow your Digits related scenarios. I tested it on my iPhone 6. I've just tried to completely remove the app from the device and run it from the Xcode and got the crash again.

I wrapped the crash line of code in the try catch block like this:

```
@try {
          return [NSKeyedUnarchiver unarchiveObjectWithData:latest.data];
      } @catch ( NSException *ex ) {
          NSLog(@"Exception: %@", ex);
          return nil;
      }

```
and got this:

```
(lldb) po ex
*** -[NSKeyedUnarchiver decodeObjectForKey:]: cannot decode object of class (DGTSession) for key (root); the class may be defined in source code or a library that is not linked
(
	0   CoreFoundation                      0x000000018f0411d0 <redacted> + 148
	1   libobjc.A.dylib                     0x000000018da7855c objc_exception_throw + 56
	2   Foundation                          0x000000018fae4408 <redacted> + 0
	3   Foundation                          0x000000018fae45c4 <redacted> + 444
	4   Foundation                          0x000000018fab01cc <redacted> + 376
	5   Foundation                          0x000000018faaffa8 <redacted> + 308
	6   Foundation                          0x000000018faaf168 <redacted> + 88
	7   DigitsMigrationHelper               0x0000000100857fbc -[FIRDigitsSessionStore getSession] + 212
	8   DigitsMigrationHelper               0x0000000100856118 __35-[FIRDigitsMigrator getLegacyAuth:]_block_invoke + 72
	9   libdispatch.dylib                   0x0000000101511258 _dispatch_call_block_and_release + 24
	10  libdispatch.dylib                   0x0000000101511218 _dispatch_client_callout + 16
	11  libdispatch.dylib                   0x000000010151f26c _dispatch_queue_override_invoke + 980
	12  libdispatch.dylib                   0x0000000101520e2c _dispatch_root_queue_drain + 584
	13  libdispatch.dylib                   0x0000000101520b78 _dispatch_worker_thread3 + 140
	14  libsystem_pthread.dylib             0x000000018e0d32a0 _pthread_wqthread + 1288
	15  libsystem_pthread.dylib             0x000000018e0d2d8c start_wqthread + 4
)
```

Maybe this will help you.

**Comment by mylyuic** [comment]
@aetsyss , thanks for the info. I could reproduce the issue on my side now. Will create a PR to get it fixed.

**Comment by mylyuic** [comment]
@aetsyss , released a newer version. You can now update your pod to try it out!

**Comment by aetsyss** [comment]
@mylyuic thnx for the fix. Now it works fine!
